import { sqliteTable, text, integer, index, uniqueIndex } from "drizzle-orm/sqlite-core";

export const articles = sqliteTable(
  "articles",
  {
    id: text("id").primaryKey(),
    title: text("title").notNull(),
    slug: text("slug").notNull(),
    excerpt: text("excerpt").notNull(),
    content: text("content").notNull(), // Supports HTML generated by compiler/script
    category: text("category").notNull(),
    image: text("image").notNull(),
    author: text("author").notNull(),
    publishedAt: integer("published_at").notNull(), // Epoch timestamp (ms)
    createdAt: integer("created_at").notNull(),
    updatedAt: integer("updated_at").notNull(),
    featured: integer("featured").notNull().default(0), // SQLite stores booleans as 0 or 1
    status: text("status").notNull().default("published"), // 'draft' or 'published'
    metaTitle: text("meta_title"),
    metaDescription: text("meta_description"),
    keywords: text("keywords"),
    readingTime: integer("reading_time").notNull().default(0), // In minutes
    views: integer("views").notNull().default(0),

    // Content Intelligence Upgrades
    tags: text("tags"), // Comma-separated tags
    contentType: text("content_type").notNull().default("news"), // "news" | "tutorial" | "comparison" | "tool-review" | "career"
    viralScore: integer("viral_score").default(0),
    sourceName: text("source_name"),
    sourceUrl: text("source_url"),

    // Weekly / Monthly Views and recency tracking
    views7d: integer("views_7d").notNull().default(0),
    views30d: integer("views_30d").notNull().default(0),
    lastViewedAt: integer("last_viewed_at"),

    // Social Metadata overrides
    ogImage: text("og_image"),
    twitterImage: text("twitter_image"),

    // Publishing context
    publishedBy: text("published_by").default("Kampus Filter Editorial"),
    researchRef: text("research_ref"),
    metadata: text("metadata")
  },
  (table) => ({
    slugIdx: uniqueIndex("slug_idx").on(table.slug),
    categoryIdx: index("category_idx").on(table.category),
    publishedAtIdx: index("published_at_idx").on(table.publishedAt),
    featuredIdx: index("featured_idx").on(table.featured),

    // Composite indexes for query optimizations
    statusCategoryIdx: index("status_category_idx").on(table.status, table.category),
    statusDateIdx: index("status_date_idx").on(table.status, table.publishedAt),
    trendingIdx: index("trending_idx").on(table.status, table.views7d, table.publishedAt),
    viralScoreIdx: index("viral_score_idx").on(table.viralScore),
    contentTypeIdx: index("content_type_idx").on(table.contentType),
    tagsIdx: index("tags_idx").on(table.tags)
  })
);

export type Article = typeof articles.$inferSelect;
export type NewArticle = typeof articles.$inferInsert;
